In [1]:
import numpy as np

In [172]:
# sudoku to solve
mat_main = np.array([[7,2,0,0,0,6,1,0,0],
       [6,0,0,0,1,0,0,0,4],
       [8,0,9,0,0,3,0,0,5],
       [0,0,0,0,4,0,0,0,0],
       [0,0,0,8,5,2,0,0,7],
       [0,5,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,5,0,3],
       [2,0,0,6,3,0,4,0,0],
       [0,0,0,2,0,0,0,7,9]])
mat_main

array([[7, 2, 0, 0, 0, 6, 1, 0, 0],
       [6, 0, 0, 0, 1, 0, 0, 0, 4],
       [8, 0, 9, 0, 0, 3, 0, 0, 5],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 8, 5, 2, 0, 0, 7],
       [0, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 5, 0, 3],
       [2, 0, 0, 6, 3, 0, 4, 0, 0],
       [0, 0, 0, 2, 0, 0, 0, 7, 9]])

In [148]:
def check(n,i,j,mat):
    # function to check if a placement of a number is valid or not
    if n in mat[i] or n in mat[:,j] or n in mat[(i//3)*3:(3+(i//3)*3), (j//3)*3:(3+(j//3)*3)]:
        return False
    return True

In [149]:
def check_matrix(n, row, col, mat):
    check_col=[]
    check_row=[]
    check_box=[]
    for i in range(9):
        if mat[i][col]!=0:
            continue
        
        if check(n,i,col,mat):
            check_col.append(i)
    if len(check_col)==1:
        mat[check_col[0]][col]=n
    
    for j in range(9):
        if mat[row][j]!=0:
            continue
        
        if check(n,row,j,mat):
            check_row.append(j)
    if len(check_row)==1:
        mat[row][check_row[0]]=n
            
    for i in range((row//3)*3, 3+(row//3)*3):
        for j in range((col//3)*3, 3+(col//3)*3):
            if mat[i][j]!=0:
                continue
            
            if check(n,i,j,mat):
                check_box.append((i,j))
    if len(check_box)==1:
        mat[check_box[0][0]][check_box[0][1]]=n
        
    return mat
                
                

In [151]:
# main solver
for i in range(9):
    for j in range(9):
        for n in range(9):
            mat_main = check_matrix(n+1,i,j, mat_main)
mat_main

# Run twice for a complex sudoku.

array([[7, 2, 4, 5, 9, 6, 1, 3, 8],
       [6, 3, 5, 7, 1, 8, 2, 9, 4],
       [8, 1, 9, 4, 2, 3, 7, 6, 5],
       [3, 7, 2, 1, 4, 9, 8, 5, 6],
       [9, 6, 1, 8, 5, 2, 3, 4, 7],
       [4, 5, 8, 3, 6, 7, 9, 1, 2],
       [1, 8, 6, 9, 7, 4, 5, 2, 3],
       [2, 9, 7, 6, 3, 5, 4, 8, 1],
       [5, 4, 3, 2, 8, 1, 6, 7, 9]])

In [152]:
# checking if the solution is right
for i in range(9):
    print(np.sum(mat_main[i]), np.sum(mat_main[:,i]))

45 45
45 45
45 45
45 45
45 45
45 45
45 45
45 45
45 45


### Using Backtracking

In [173]:
def sudoku_trial(row, col, mat):
    
    if row==9:
        return True
    elif col == 9:
        row=row+1
        col=0
        return sudoku_trial(row,col,mat)
                
    if mat[row][col]!=0:
        return sudoku_trial(row,col+1,mat)
        
    for n in range(1,10):
        if check(n,row,col,mat):
            mat[row][col]=n
            if sudoku_trial(row,col+1,mat):
                return True
        mat[row][col]=0
        
    return False           

In [174]:
sudoku_trial(0,0,mat_main)
mat_main

array([[7, 2, 4, 5, 9, 6, 1, 3, 8],
       [6, 3, 5, 7, 1, 8, 2, 9, 4],
       [8, 1, 9, 4, 2, 3, 7, 6, 5],
       [3, 7, 2, 1, 4, 9, 8, 5, 6],
       [9, 6, 1, 8, 5, 2, 3, 4, 7],
       [4, 5, 8, 3, 6, 7, 9, 1, 2],
       [1, 8, 6, 9, 7, 4, 5, 2, 3],
       [2, 9, 7, 6, 3, 5, 4, 8, 1],
       [5, 4, 3, 2, 8, 1, 6, 7, 9]])

In [166]:
# checking if the solution is right
for i in range(9):
    print(np.sum(mat_main[i]), np.sum(mat_main[:,i]))

45 45
45 45
45 45
45 45
45 45
45 45
45 45
45 45
45 45


In [ ]:
def sudoku(row, col, mat):
    global memory
    if row==9:
        return True
    elif col == 9:
        row=row+1
        col=0
               
    if mat[row][col]!=0:
        return sudoku(row,col+1,mat)
        
    else:
        for n in range(1,10):
            ans = check(n,row, col,mat)
            if ans==0:
                mat[row][col]=n
                
                memory.append([row,col,n])
                print(memory)
                sudoku(row,col+1,mat)
                
        for i,j,k in reversed(memory):
            if k==9:
                mat[i][j]=0
                memory = memory[:-1]
            else:
                ans =  check(k+1,i,j,mat)
                if ans==0:
                    mat[i][j]=k+1
                    memory = memory[:-1]
                    memory.append([i,j,k+1])
                    sudoku(i,j+1,mat)
                elif ans!=0 & k==8:
                    mat[i][j]=0
                    memory = memory[:-1]
                    continue
                else:
                    while(k<8):
                        k = k+1
                        ans = check(k+1,i,j,mat)
                        if ans ==0:
                            mat[i][j]=k+1
                            memory = memory[:-1]
                            memory.append([i,j,k+1])
                            sudoku(i,j+1,mat)
            
    #return('solution not possible')
    